version: "3.7"

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: test1
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "80:80"
    tty: true
    networks:
      - test

networks:
  test:
    driver: bridge
