---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mydeploy
  name: mydeploy
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydeploy
  template:
    metadata:
      labels:
        app: mydeploy
    spec:
      containers:
      - image: siddharthgopalpatel/dcp_devsecops:latest
        name: sidd
        volumeMounts:
          - name: data
            mountPath: /var/log/gunicorn
        env:
          - name: OPENAI_API_KEY
            valueFrom:
              secretKeyRef:
                name: db-secret  ## Name of the secret created
                key: siddnidhi  ## The key to fetch
      volumes:
      - name: data
        persistentVolumeClaim:
           claimName: data
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: myservice
  name: myservice
  namespace: project
spec:
  ports:
  - name: "8000"
    port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 30000
  selector:
    app: mydeploy
  type: NodePort
